# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    settings:
      classic_compatible: true #¥¶¿Ìø’÷µ
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

